import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideMenu from "./packages/ui/common/SideMenu";
import AuthProvider from "./packages/providers/AuthProvider";
import CheckSession from "./packages/providers/CheckSession";
import CheckOnlineStatus from "./packages/providers/CheckOnlineStatus";
import { Suspense } from "react";
import Loading from './loading'



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Suspense fallback={<Loading/>}>

          <AuthProvider>
            {/* <CheckSession> */}

            <CheckOnlineStatus>
              <SideMenu />
              {/* <div className='p-10'> */}
              {children}

              {/* </div> */}

              {/* </CheckSession> */}
            </CheckOnlineStatus>
          </AuthProvider>
        
       </Suspense>
      </body>
    </html>
  );
}
